services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-chatbot
    ports:
      - "8502:8502"
    volumes:
      - ./secret.yaml:/secret.yaml
      - ./.env:/.env
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: always